import Head from "next/head";

import Products from "~/components/Products";

export default function Home() {

  return (
    <>
      <Head>
        <title>CORAL</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex-center mb-16'>
        <Products />
      </main>
    </>
  );
}
